name: Upload to S3 Action pipeline

on:
  push:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: generate-version
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up environment
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/next' ||
          github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{secrets.PIPELINE_GITHUB_TOKEN}}
        run: |
          npm config set always-auth true
          npm config set //npm.pkg.github.com/:_authToken $GH_TOKEN
          npm config set @3dwardCh3nG:registry https://npm.pkg.github.com
          yarn install
      - name: Generate App Version
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/next' ||
          github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{secrets.PIPELINE_GITHUB_TOKEN}}
        shell: bash
        run: bash ./scripts/generate-version.sh ${{ steps.branch-name.outputs.current_branch }}
