name: Upload to S3 Action pipeline

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]
permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: generate-version
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
      - name: Set up environment
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/next' ||
          github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{secrets.PIPELINE_GITHUB_TOKEN}}
        run: |
          yarn install
      - name: Generate App Version
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/next' ||
          github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{secrets.PIPELINE_GITHUB_TOKEN}}
        shell: bash
        run: bash ./scripts/generate-version.sh ${{ steps.branch-name.outputs.current_branch }}
